name:               sweetfish
version:            0.0.6
base:               core18
icon:               snap/gui/sweetfish.png
license:            Apache-2.0
summary:            Mastodon client for Linux
description:        The Mastodon client for linux/X11.This software uses qt.So it may be possible to work on macOS or Windows.
confinement:        strict
grade:              stable

architectures:
  - build-on:       amd64
  - build-on:       i386
  - build-on:       arm64

apps:
  sweetfish:
    command:        bin/desktop-launch sweetfish
    plugs:
      - audio-playback
      - desktop-legacy
      - desktop
      - home
      - network
      - pulseaudio
      - wayland
      - x11
      - unity7

parts:
  sweetfish:
    source:         https://github.com/PG-MANA/Sweetfish.git
    source-type:    git
    plugin:         cmake
    build-packages: [g++, qtbase5-dev, qttools5-dev, libphonon4qt5-dev]
    after:          [desktop-qt5]
    stage-packages:
      - libasyncns0
      - libdouble-conversion1
      - libflac8
      - libfreetype6
      - libgl1
      - libglvnd0
      - libglx0
      - libgraphite2-3
      - libharfbuzz0b
      - libicu60
      - libogg0
      - libphonon4qt5-4
      - libpng16-16
      - libpulse-mainloop-glib0
      - libpulse0
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5network5
      - libqt5widgets5
      - libsndfile1
      - libvorbis0a
      - libvorbisenc2
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages: [qtbase5-dev, dpkg-dev]
