name:               sweetfish
version:            0.7.1
base:               core24
icon:               snap/gui/sweetfish.png
license:            Apache-2.0
summary:            Mastodon client for Linux
description:        The Mastodon client for Linux
confinement:        strict
grade:              stable

architectures:
  - build-on:       amd64
  - build-on:       arm64

apps:
  sweetfish:
    command:        bin/desktop-launch sweetfish
    plugs:
      - audio-playback
      - desktop-legacy
      - desktop
      - home
      - network
      - pulseaudio
      - wayland
      - x11
      - unity7
    extensions:     [kde-neon]

parts:
  sweetfish:
    source:         https://github.com/PG-MANA/Sweetfish.git
    source-type:    git
    plugin:         cmake
    build-packages: 
      - g++
      - libglx-dev
      - libgl1-mesa-dev
      - qt6-base-dev
      - qt6-tools-dev
      - qt6-tools-dev-tools
      - qt6-l10n-tools
      - qt6-multimedia-dev
      - libphonon4qt6-dev
    stage-packages:
      - libqt6core6
      - libqt6dbus6
      - libqt6gui6
      - libqt6network6
      - libqt6widgets6
      - libqt6multimedia6
      - libphonon4qt6-4
