name:               sweetfish
version:            0.0.7
base:               core22
icon:               snap/gui/sweetfish.png
license:            Apache-2.0
summary:            Mastodon client for Linux
description:        The Mastodon client for linux/X11.This software uses qt.So it may be possible to work on macOS or Windows.
confinement:        strict
grade:              stable

architectures:
  - build-on:       amd64
  - build-on:       arm64

apps:
  sweetfish:
    command:        bin/desktop-launch sweetfish
    plugs:
      - audio-playback
      - desktop-legacy
      - desktop
      - home
      - network
      - pulseaudio
      - pipewire
      - wayland
      - x11
      - unity7

parts:
  sweetfish:
    source:         https://github.com/PG-MANA/Sweetfish.git
    source-type:    git
    plugin:         cmake
    build-packages: 
      - g++
      - qtbase5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - libphonon4qt5-dev
      - libphonon4qt5experimental-dev
    after:          [desktop-qt]
    stage-packages:
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5network5
      - libqt5widgets5
      - libphonon4qt5-4

  desktop-qt:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - dpkg-dev
